# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: node_js

node_js:
  - "iojs"
  - "lts/*"
  - "node"

# job phases

install:
  - npm install

script:
  - npm test
